# Generated by Django 4.2.3 on 2023-08-06 06:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='unique_identifier',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=32, null=True, unique=True),
        ),
    ]
